### ISSUE TITLE
quesion: how to read file structure

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke.NETStandard#13]
Is there a way to read generic h5 file structure like the hdfview Java app using pinvoke?

**Comment by Apollo3zehn** [comment]
In another project I use H5L.Iterate() like this:
https://github.com/OneDAS-Group/OneDAS-Core/blob/master/src/OneDas.Hdf.Types/Core/GeneralHelper.cs#L51
Most of the code ist not relevant for you because it is specific for my use case but it shows the general approach.

**Comment by LiorBanai** [comment]
Thanks, I will check it out.

**Comment by LiorBanai** [comment]
@Apollo3zehn  thanks again. It helped a lot.
