### ISSUE TITLE
question: register for logs

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke.NETStandard#14]
Is there a way to register for the console output of errors and such? I would like to get all traces and  outputs in my logging framework

**Comment by Apollo3zehn** [comment]
I guess this is what you are looking for:
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5E.html#Error-RegisterClass

I did not use it myself yet, but the H5E functions (especially ```H5Eregister_class```) seem to be the right place to start.

**Comment by Apollo3zehn** [comment]
Hmm I think I am wrong, this is only to print additional errors via the HDF error API.

**Comment by LiorBanai** [comment]
In my library there are prints to console (when console is used) but are not captured in non console apps.. I wonder if there is a callback we can register to get this info.
e.g:
https://github.com/LiorBanai/HDF5-CSharp/issues/25

**Comment by Apollo3zehn** [comment]
This seems to be more promising: 
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5E.html#Error-SetAuto2

Maybe something likes this works (untested): 
```cs
class Program
{
    static void Main(string[] args)
    {
        H5E.set_auto(H5E.DEFAULT, Program.ErrorDelegateMethod, IntPtr.Zero);
    }

    public static int ErrorDelegateMethod(long estack, IntPtr client_data)
    {
        H5E.walk(estack, H5E.direction_t.H5E_WALK_DOWNWARD, Program.WalkDelegateMethod, IntPtr.Zero);
        return 0;
    }

    public static int WalkDelegateMethod(uint n, ref H5E.error_t err_desc, IntPtr client_data)
    {
        // log your error, e.g. logger.LogInformation(err_desc.desc);
        return 0;
    }
}
```

Edit: a similar example can be found here: https://github.com/HDFGroup/HDF.PInvoke/blob/11919c1852d4334555066e7dc6a96952d5d2f44a/UnitTests/H5ETest/H5Ewalk.cs

**Comment by LiorBanai** [comment]
I'll Check. Thanks!

**Comment by LiorBanai** [comment]
@Apollo3zehn, it worked great. Thanks.
I'm closing this issue.
