### ISSUE TITLE
Question: Iterate of each attribute of object and print its information

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke.NETStandard#17]
HI,
I'm able to iterate over the structure of h5 file but it does not iterate over each object attributes if there any.
Is it possible to do so (and print the attributes values, types, etc)?

**Comment by Apollo3zehn** [comment]
Did you try `H5A.iterate`? I did not work with it yet but I guess it works similar to `H5G.iterate`.

**Comment by LiorBanai** [comment]
Yeah I just gave it a test and it partially meets my needs. Thanks!
