### ISSUE TITLE
Question: Call to list all open object and how to close all of them?

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke.NETStandard#18]
Hi,
1. is there are method that list all opens objects with its information?
2. can those be close in other call or they need to be closed individually?

**Comment by Apollo3zehn** [comment]
1. I don't know
2. Maybe this helps? https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFcloseDegree

**Comment by LiorBanai** [comment]
I'll check it. Seems like good candidate. Thanks again 🙂
